language: node_js
node_js:
- '0.10'

before_install:
  - gem update --system
  - gem install sass --version "=3.4.9"
  - gem install compass --version "=1.0.1"
  - gem install compass-core --version "=1.0.1"
  - gem install compass-import-once --version "=1.0.5"
  - gem install chunky_png --version "=1.3.3"
  - gem install ffi --version "=1.9.6"
  - gem install scss-lint --version "=0.30.0"
  - gem install rb-fsevent --version "=0.9.4"
  - gem install rb-inotify --version "=0.9.5"
  - gem install multi_json --version "=1.10.1"
  - gem install rainbow --version "=2.0.0"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

env:
  - NODE_ENV="test"